const props = {
  plugins: [],
  linkTo: b => `block-${b.id}`,
  extraWidgetProps: {
    editable: false,
    mobilization: {
      body_font: null,
      color_scheme: 'beaga-scheme',
      community_id: 75,
      created_at: '2019-03-11T11:00:13.328-03:00',
      custom_domain: null,
      facebook_share_description: null,
      facebook_share_image: null,
      facebook_share_title: null,
      favicon: null,
      goal: 'Testar inserção de widgets e montagem de template',
      google_analytics_code: null,
      header_font: null,
      id: 1116,
      name: 'Template',
      slug: 'teste-de-widgets',
      status: 'active',
      tag_list: [],
      twitter_share_text:
        'Acabei de colaborar com Template. Participe você também: ',
      updated_at: '2020-04-16T20:32:02.344-03:00',
      user_id: 152,
    },
    plugins: [],
  },
  headerFont: null,
  bodyFont: null,
  colorScheme: 'beaga-scheme',
  blocks: [
    {
      bg_class: `{
        r: 240,
        g: 133,
        b: 133,
        a: 1,
      }`,
      bg_image: null,
      created_at: '2019-03-11T11:00:19.938-03:00',
      deleted_at: null,
      hidden: null,
      id: 11944,
      menu_hidden: null,
      mobilization_id: 1116,
      name: 'Home',
      position: 2,
      updated_at: '2019-06-19T09:50:44.825-03:00',
    },
    {
      bg_class: `{
        r: 118,
        g: 143,
        b: 5,
        a: 1,
      }`,
      bg_image: null,
      created_at: '2019-03-11T11:00:29.562-03:00',
      deleted_at: null,
      hidden: null,
      id: 11945,
      menu_hidden: null,
      mobilization_id: 1116,
      name: 'Block 3',
      position: 3,
      updated_at: '2020-04-16T20:17:21.282-03:00',
    },
    {
      bg_class: `{
        r: 18,
        g: 27,
        b: 172,
        a: 1,
      }`,
      bg_image: null,
      created_at: '2019-09-05T14:15:02.767-03:00',
      deleted_at: null,
      hidden: null,
      id: 13564,
      menu_hidden: null,
      mobilization_id: 1116,
      name: null,
      position: 4,
      updated_at: '2019-09-05T14:15:02.767-03:00',
    },
    {
      bg_class: null,
      bg_image: null,
      created_at: '2019-12-04T15:31:38.243-03:00',
      deleted_at: null,
      hidden: null,
      id: 14096,
      menu_hidden: null,
      mobilization_id: 1116,
      name: null,
      position: 5,
      updated_at: '2019-12-04T15:31:38.243-03:00',
    },
    {
      bg_class: null,
      bg_image: null,
      created_at: '2020-04-16T20:17:29.901-03:00',
      deleted_at: null,
      hidden: null,
      id: 14823,
      menu_hidden: null,
      mobilization_id: 1116,
      name: null,
      position: 6,
      updated_at: '2020-04-16T20:17:29.901-03:00',
    },
  ],
  blocksIsLoaded: true,
  editable: false,
  mobilization: {
    body_font: null,
    color_scheme: 'beaga-scheme',
    community_id: 75,
    created_at: '2019-03-11T11:00:13.328-03:00',
    custom_domain: null,
    facebook_share_description: null,
    facebook_share_image: null,
    facebook_share_title: null,
    favicon: null,
    goal: 'Testar inserção de widgets e montagem de template',
    google_analytics_code: null,
    header_font: null,
    id: 1116,
    name: 'Template',
    slug: 'teste-de-widgets',
    status: 'active',
    tag_list: [],
    twitter_share_text:
      'Acabei de colaborar com Template. Participe você também',
    updated_at: '2020-04-16T20:32:02.344-03:00',
    user_id: 152,
  },
  widgets: [
    {
      action_community: false,
      action_opportunity: false,
      block_id: 11944,
      count: 0,
      created_at: '2019-03-11T11:00:19.940-03:00',
      donations_count: 0,
      exported_at: null,
      form_entries_count: 0,
      goal: null,
      id: 20291,
      kind: 'content',
      lg_size: 12,
      match_list: [],
      md_size: 12,
      settings: {
        object: 'value',
        document: {
          object: 'document',
          data: {},
          nodes: [
            {
              object: 'block',
              type: 'line',
              data: {},
              nodes: [
                {
                  object: 'text',
                  leaves: [
                    {
                      object: 'leaf',
                      text: 'Clique para editar a ferramen',
                      marks: [],
                    },
                  ],
                },
                {
                  object: 'inline',
                  type: 'imageLink',
                  data: {
                    src:
                      '//s3.amazonaws.com/hub-central/uploads/1587079912_icon.svg',
                    href: 'https://twitter.com',
                  },
                  nodes: [
                    {
                      object: 'text',
                      leaves: [
                        {
                          object: 'leaf',
                          text: '',
                          marks: [],
                        },
                      ],
                    },
                  ],
                },
                {
                  object: 'text',
                  leaves: [
                    {
                      object: 'leaf',
                      text: 'ta',
                      marks: [],
                    },
                  ],
                },
              ],
            },
            {
              object: 'block',
              type: 'line',
              data: {},
              nodes: [
                {
                  object: 'text',
                  leaves: [
                    {
                      object: 'leaf',
                      text: '',
                      marks: [],
                    },
                  ],
                },
              ],
            },
            {
              object: 'block',
              type: 'line',
              data: {},
              nodes: [
                {
                  object: 'text',
                  leaves: [
                    {
                      object: 'leaf',
                      text: '',
                      marks: [],
                    },
                  ],
                },
                {
                  object: 'inline',
                  type: 'embed',
                  data: {
                    embed:
                      '<iframe width="560" height="315" src="https://www.youtube.com/embed/siOIslfOyZY" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
                  },
                  nodes: [
                    {
                      object: 'text',
                      leaves: [
                        {
                          object: 'leaf',
                          text: '',
                          marks: [],
                        },
                      ],
                    },
                  ],
                },
                {
                  object: 'text',
                  leaves: [
                    {
                      object: 'leaf',
                      text: '',
                      marks: [],
                    },
                  ],
                },
              ],
            },
          ],
        },
      },
      sm_size: 12,
      updated_at: '2020-04-16T20:32:02.342-03:00',
    },
    {
      action_community: false,
      action_opportunity: true,
      block_id: 11945,
      count: 0,
      created_at: '2019-03-11T11:00:29.563-03:00',
      donations_count: 0,
      exported_at: null,
      form_entries_count: 0,
      goal: null,
      id: 20292,
      kind: 'form',
      lg_size: 6,
      match_list: [],
      md_size: 6,
      settings: {
        email_text:
          'Obrigado por apostar na força da ação coletiva! Sua participação é muito importante e, agora, precisamos da sua ajuda para potencializar nosso impacto. Compartilhe nas suas redes clicando em um dos links abaixo. Um abraço',
        fields: [
          {
            kind: 'text',
            label: 'Nome',
            placeholder: 'Insira seu nome',
            required: 'true',
            uid: 'field-1552312909841-49',
          },
          {
            kind: 'email',
            label: 'Email',
            placeholder: 'Insira seu e-mail',
            required: 'true',
            uid: 'field-1552312920353-15',
          },
          {
            kind: 'dropdown',
            label: 'Região onde reside',
            placeholder: 'Norte,Nordeste,Centro-Oeste,Sudeste,Sul',
            required: 'true',
            uid: 'field-1552312933368-45',
          },
        ],
      },
      sm_size: 12,
      updated_at: '2019-03-11T11:03:20.184-03:00',
    },
    {
      action_community: false,
      action_opportunity: false,
      block_id: 11945,
      count: 0,
      created_at: '2019-03-11T11:00:29.571-03:00',
      donations_count: 0,
      exported_at: null,
      form_entries_count: 0,
      goal: '40000.0',
      id: 20293,
      kind: 'content',
      lg_size: 6,
      match_list: [],
      md_size: 6,
      settings: {
        content: {
          object: 'value',
          document: {
            object: 'document',
            data: {},
            nodes: [
              {
                object: 'block',
                type: 'line',
                data: {},
                nodes: [
                  {
                    object: 'text',
                    leaves: [
                      {
                        object: 'leaf',
                        text: 'Click here to edit...',
                        marks: [],
                      },
                    ],
                  },
                ],
              },
            ],
          },
        },
      },
      sm_size: 12,
      updated_at: '2020-04-16T20:17:05.417-03:00',
    },
    {
      action_community: false,
      action_opportunity: false,
      block_id: 13564,
      count: 0,
      created_at: '2019-09-05T14:15:02.769-03:00',
      donations_count: 0,
      exported_at: null,
      form_entries_count: 0,
      goal: null,
      id: 23193,
      kind: 'content',
      lg_size: 4,
      match_list: [],
      md_size: 6,
      settings: {
        content: {
          object: 'value',
          document: {
            object: 'document',
            data: {},
            nodes: [
              {
                object: 'block',
                type: 'line',
                data: {},
                nodes: [
                  {
                    object: 'text',
                    leaves: [
                      {
                        object: 'leaf',
                        text: 'Clique para editar a ferramenta',
                        marks: [],
                      },
                    ],
                  },
                ],
              },
            ],
          },
        },
      },
      sm_size: 12,
      updated_at: '2019-09-05T14:15:12.431-03:00',
    },
    {
      action_community: false,
      action_opportunity: false,
      block_id: 13564,
      count: 0,
      created_at: '2019-09-05T14:15:02.778-03:00',
      donations_count: 0,
      exported_at: null,
      form_entries_count: 0,
      goal: null,
      id: 23194,
      kind: 'pressure-phone',
      lg_size: 8,
      match_list: [],
      md_size: 6,
      settings: {
        main_color: '#f23392',
        title_text: 'Ligue para quem pode tomar ,essa decisão',
        button_text: 'Ligar',
      },
      sm_size: 12,
      updated_at: '2019-09-05T14:15:19.324-03:00',
    },
    {
      action_community: false,
      action_opportunity: false,
      block_id: 14096,
      count: 0,
      created_at: '2019-12-04T15:31:38.247-03:00',
      donations_count: 0,
      exported_at: null,
      form_entries_count: 0,
      goal: null,
      id: 24146,
      kind: 'draft',
      lg_size: 4,
      match_list: [],
      md_size: 6,
      settings: null,
      sm_size: 12,
      updated_at: '2019-12-04T15:31:38.247-03:00',
    },
    {
      action_community: false,
      action_opportunity: false,
      block_id: 14096,
      count: 0,
      created_at: '2019-12-04T15:31:38.256-03:00',
      donations_count: 0,
      exported_at: null,
      form_entries_count: 0,
      goal: null,
      id: 24147,
      kind: 'donation',
      lg_size: 8,
      match_list: [],
      md_size: 6,
      settings: {
        button_text: 'Give Now',
        email_subject: 'vc doou',
        email_text: 'obrigada',
        main_color: '#54d0f6',
        sender_email: 'viviane@nossas.org',
        sender_name: 'viviane',
        title_text: 'Click to set up your donation bl',
      },
      sm_size: 12,
      updated_at: '2020-04-03T15:02:15.685-03:00',
    },
    {
      action_community: false,
      action_opportunity: false,
      block_id: 14823,
      count: 0,
      created_at: '2020-04-16T20:17:29.902-03:00',
      donations_count: 0,
      exported_at: null,
      form_entries_count: 0,
      goal: null,
      id: 25516,
      kind: 'draft',
      lg_size: 12,
      match_list: [],
      md_size: 12,
      settings: null,
      sm_size: 12,
      updated_at: '2020-04-16T20:17:29.902-03:00',
    },
  ],
};

export default props;
