workspace:
  base: /code

pipeline:
  test:
    image: node:14-alpine
    commands:
      - npm i
      - npm run lint
      - npm run test
    when:
      event: [push, tag]
      
  build:
    image: node:14-alpine
    commands:
      - npm run build-prod
    group: build
    when:
      status: success
      branch: [hotfix/*, release/*, feature/*, support/*, develop]
            
  # publish-package-npm:
  #   image: plugins/npm
  #   secrets: [npm_auth_token, npm_username, npm_email, npm_password]
  #   settings:
  #     username:
  #       from_secret: npm_username
  #     token:
  #       from_secret: npm_auth_token
  #     email:
  #       from_secret: npm_email
  #     password:
  #       from_secret: npm_password
  #   group: publish
  #   when:
  #     event: [push, tag]

  # build-public-ts:
  #   image: node:12-alpine
  #   commands:
  #     - cd bonde-public
  #     - yarn
  #     - yarn build
  #   when:
  #     event: [push, tag]
  
  # unit-tests:
  #   image: node:12-alpine
  #   environment:
  #     - SKIP_PREFLIGHT_CHECK=true
  #   commands:
  #     - cd bonde-public
  #     - yarn run coverage
  #   when:
  #     event: [push, tag]

  staging-publish-public-ts:
    image: plugins/docker
    repo: nossas/bonde-public-ts
    secrets: [ docker_username, docker_password ]
    # dockerfile: bonde-public/Dockerfile
    # context: bonde-public/
    group: publish
    tags:
      - ${DRONE_BRANCH/\//-}
    when:
      status: success
      branch: [hotfix/*, release/*, feature/*, support/*]
  
  production-publish-public-ts:
    image: plugins/docker
    repo: nossas/bonde-public-ts
    secrets: [ docker_username, docker_password ]
    # dockerfile: bonde-public/Dockerfile
    # context: bonde-public/
    group: publish
    tags:
      - ${DRONE_TAG##v}
      - latest
    when:
      status: success
      event: tag
  
  staging-deploy-public-ts:
    image: peloton/drone-rancher
    url: http://cluster.bonde.org
    service: webservers/public-ts
    docker_image: nossas/bonde-public-ts:${DRONE_BRANCH/\//-}
    timeout: 360
    confirm: true
    group: deploy
    secrets: [ rancher_access_key, rancher_secret_key ]
    when:
      status: success
      branch: [hotfix/*, release/*, feature/*, support/*]

  production-deploy-public-ts:
    image: peloton/drone-rancher
    url: http://cluster.bonde.org
    service: webservers/public-ts
    docker_image: "nossas/bonde-public-ts:${DRONE_TAG##v}"
    timeout: 360
    confirm: true
    group: deploy
    secrets:
      - source: rancher_access_key_prod
        target: rancher_access_key
      - source: rancher_secret_key_prod
        target: rancher_secret_key
    when:
      status: success
      event: tag
