workspace:
  base: /code

pipeline:
  # build-package:
  #   image: node:12-alpine
  #   commands:
  #     - yarn
  #   when:
  #     event: [push, tag]
      
  # tests:
  #   image: node:12-alpine
  #   commands:
  #     - yarn run lint
  #     - yarn run test
  #   group: build
  #   when:
  #     status: success
  #     branch: [hotfix/*, release/*, feature/*, support/*, develop]
            
  # publish-package-npm:
  #   image: plugins/npm
  #   secrets: [npm_auth_token, npm_username, npm_email, npm_password]
  #   settings:
  #     username:
  #       from_secret: npm_username
  #     token:
  #       from_secret: npm_auth_token
  #     email:
  #       from_secret: npm_email
  #     password:
  #       from_secret: npm_password
  #   group: publish
  #   when:
  #     status: success
  #     event: push
  #     branch: [hotfix/*, release/*, feature/*, support/*]

  build-public-ts:
    image: node:12-alpine
    commands:
      - cd example
      - yarn
      - yarn build
    when:
      event: [push, tag]
  
  unit-tests:
    image: node:12-alpine
    environment:
      - SKIP_PREFLIGHT_CHECK=true
    commands:
      - cd example
      - yarn run coverage
    when:
      event: [push, tag]

  staging-publish-public-ts:
    image: plugins/docker
    repo: nossas/bonde-public-ts
    secrets: [ docker_username, docker_password ]
    dockerfile: example/Dockerfile
    context: example/
    group: publish
    tags:
      - ${DRONE_BRANCH/\//-}
    when:
      status: success
      branch: [hotfix/*, release/*, feature/*, support/*]
  
  production-publish-public-ts:
    image: plugins/docker
    repo: nossas/bonde-public-ts
    secrets: [ docker_username, docker_password ]
    dockerfile: example/Dockerfile
    context: example/
    group: publish
    tags:
      - ${DRONE_TAG##v}
      - latest
    when:
      status: success
      event: tag
  
  staging-deploy-public-ts:
    image: peloton/drone-rancher
    url: http://cluster.bonde.org
    service: webservers/public-ts
    docker_image: nossas/bonde-public-ts:${DRONE_BRANCH/\//-}
    timeout: 360
    confirm: true
    group: deploy
    secrets: [ rancher_access_key, rancher_secret_key ]
    when:
      status: success
      branch: [hotfix/*, release/*, feature/*, support/*]

  production-deploy-public-ts:
    image: peloton/drone-rancher
    url: http://cluster.bonde.org
    service: webservers/public-ts
    docker_image: "nossas/bonde-public-ts:${DRONE_TAG##v}"
    timeout: 360
    confirm: true
    group: deploy
    secrets:
      - source: rancher_access_key_prod
        target: rancher_access_key
      - source: rancher_secret_key_prod
        target: rancher_secret_key
    when:
      status: success
      event: tag
